### ISSUE TITLE
`Lsm6ds33::new` is hard to use properly

### ISSUE THREAD

**Issue by quentinmit** [nnarain/lsm6ds33#4]
The `new` constructor returns a `Result<Self, Error>`, which means that when it fails to check if the chip is present, it swallows the passed-in `I2C` instance and it can never be used again.

I'm not sure what the best fix is; how would you feel about returning `Result<Self, (I2C, Error)>` so that the caller gets their `I2C` object back again? I don't know if that's particularly idiomatic.

**Comment by nnarain** [comment]
Ya that's a good point. Not opposed to `Result<Self, (I2C, Error)>`. The MPU6050 driver has an explicit `init` function.  So perhaps another option is to add an `init` and then a `free(self) -> I2C` function that returns the `I2C` peripheral.

**Comment by quentinmit** [comment]
I thought about an `init` method, but that would mean it's possible to call a method on a not-yet-`init`ed instance. I just sent https://github.com/nnarain/lsm6ds33/pull/5 for the change to `new`.

**Comment by nnarain** [comment]
Ah yes that's a good point
